### PR TITLE
Mentionbomb

### PR DESCRIPTION
**Pull request by mellowagain**
image

I'm not even sure if this will get accepted but I found it fun to fuck with friends that think removing the `@everyone` permission from me could change anything >:).

Most public bots that have moderation features automatically remove the message so public servers aren't much at risk.

### CODE REVIEW

**Comment by LemonatedCat** [comment]
Copy pasted into my node.js bot and ported 😹

**Comment by delet-this** [comment]
die

**Comment by mellowagain** [comment]
image

**Comment by appu1232** [comment]
🤔 I'm not sure it's a good idea to approve this from our standpoint. With how selfbots are already in the gray area, we don't want to add cogs like this and end up with more even fingers pointed at us.

**Pull request closed without merging**
