### PR TITLE
i made a cog

### PR DESCRIPTION
**Pull request by cthpw103**
it sucks i know :P 
ill update it when i have free time.

### CODE REVIEW

**Comment by LyricLy** [comment]
The JSON file goes in the cogs folder, not the root directory. Also, that's not how the dependencies work. `urllib` is part of the standard library, `cStringIO` doesn't actually exist and Pillow is already in the main bot dependencies. You're also defining the dependencies wrong, it should be `["pillow", "urllib", "cStringIO"]`.

**Comment by LyricLy** [comment]
The JSON file goes in the cogs folder, not the root directory.

**Comment by cthpw103** [comment]
oh ok.

**Comment by LyricLy** [comment]
It seems that your code does not work with the current revision of the bot. Please test your code and come back when it is actually working.

**Comment by cthpw103** [comment]
okay.

**Pull request merged**
