### PR TITLE
Make the site nicer

### PR DESCRIPTION
**Pull request by GriffinG1**
I'm planning to add hyperlinks to each cog's raw github link later, however it is late right now

### CODE REVIEW

**Comment by LyricLy** [comment]
It's a bad idea to have the list of cogs be hard-coded. It's just another thing to remember, and the list can easily become outdated if somebody forgets. Besides, I don't see a purpose in it when the `cog list` command exists.

**Comment by GriffinG1** [comment]
It's still helpful for anyone who comes across the site. Remember, the wiki for the selfbot currently links to https://github.com/LyricLy/Selfbot-Cogs/tree/master/cogs, which isn't very helpful for anyone who wants to see what's available in an easy to read (esp on mobile) area. Also, we're at the point where new cogs aren't being added too frequently, and you could just add it to https://github.com/LyricLy/ASCII/wiki/Adding-a-cog-to-the-server

**Comment by LyricLy** [comment]
I may figure out some method of listing the current cogs in the future, but this is not that method.

**Comment by GriffinG1** [comment]
This is still a temporary solution, which can be removed at a later date

**Pull request closed without merging**
